### PR TITLE
Add config command

### PR DESCRIPTION
**Pull request by ulyssessouza**
**What I did**
Add config command

**Related issue**
Resolves https://github.com/docker/compose-cli/issues/937

### CODE REVIEW

**Comment by ndeloof** [comment]
Why didn't you just made `config` an alias for `convert`?

**Comment by ulyssessouza** [comment]
@ndeloof IMO it should be the other way around. 
`convert` to be an alias of `config`, since `config` already exists in `docker-compose` and is well known.
Then we just have to add the option for `format` on it.

**Comment by ndeloof** [comment]
I'm fine we make `config` the default command name and `convert` an alias.
I can't see the benefit of having a `--format` option other than selecting `json|yaml`. There's no mean to ask generating `cloudformation` format but on ECS.

That's why I liked `convert` as a command to produce the platform's canonical format. Would be cloudformation for ECS context, plain compose-spec on local engine

**Comment by ulyssessouza** [comment]
@ndeloof Got it! The idea was to have a way to overwrite the context to generate something different from what the context says, but thinking again, we can always use global option `--context` to select another context/type to generate another format. I'll remove that option then

**Comment by ndeloof** [comment]
By the way, #937 is about `config` entries in the compose file mounted into containers, not about `docker compose config` command

**Review by ndeloof — CHANGES_REQUESTED** [review]
IMHO we don't need a new command in the API. Just rename `Convert` and make `convert` an alias for the config command.
`ProjectConfigView` is still relevant as the local implementation for `Convert` dump way too much things. Another way would be to fix compose-go so `Project` can be Loaded then marshalled without adding unexpected stuff to the yaml stream.

**Comment by gtardif** [comment]
Discussing a bit with @ndeloof, it makes sense to keepp the `--format` option only for yaml / json, and use context for switching between cloudformation, composefile or other output. One argument for this specifically is that for cloudformation, we need an actual connection to ECS to generate the template, so this can't be done without an ECS context anyway. 
Indeed the marshalling issue needs to be addressed, but I'd rather make sure the compose.Project struct in compose-go is something we can marshall from anywhere properly and use as a reference for compose files, so hide relevant fields in compose-go. 
The config / convert alias is actually already in the main branch, from https://github.com/docker/compose-cli/pull/1216, so we can close this PR I think.

**Pull request closed without merging**
