### PR TITLE
stop using helm fork for oras dependency conflict

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like the linter is picky

**Comment by thaJeztah** [comment]
Possibly gRPC and some of the other deps may need to be pinned to older versions 🤔 they're the usual suspects, and often are incompatible 

Or ignore the linting errors, but possibly some changes would still be needed in the local code and/or elsewhere (haven't looked closely)

**Review by mat007 — APPROVED** [review]
Makes sense!

**Review by ulyssessouza — APPROVED** [review]
LGTM

**Pull request merged**
