### PR TITLE
NLB don't support securityGroups

### PR DESCRIPTION
**Pull request by ndeloof**
**What I did**
Don't set security groups for NLBs

/test-ecs

### CODE REVIEW

**Review by aiordache — APPROVED** [review]
LGTM

**Comment by mottati** [comment]
Question:  Does this patch address the error I am seeing when using this syntax in my docker compose?

```
version: '3'
x-aws-vpc: vpc-XXXXXXXXXX870cb

services:
  nginx:
    image: nginx:latest
    networks:
      - back_tier
    ports:
      - "80:80"

networks:
  back_tier:
    external: true
    name: "sg-XXXXXXXXX2cfa0"
```

Error message generated when attempting `docker compose up` command
```
docker compose up
WARN[0001] networks.external: unsupported attribute
[+] Running 13/13
 ⠿ nginxaws                                   DELETE_COMPLETE                                                                                                           230.0s
 ⠿ NginxawsSg056000683b6f2cfa0Network         DELETE_COMPLETE                                                                                                           194.2s
 ⠿ Cluster                                    DELETE_COMPLETE                                                                                                           178.0s
 ⠿ NginxTaskExecutionRole                     DELETE_COMPLETE                                                                                                           181.0s
 ⠿ NginxTCP80TargetGroup                      DELETE_COMPLETE                                                                                                           178.0s
 ⠿ CloudMap                                   DELETE_COMPLETE                                                                                                           225.0s
 ⠿ LogGroup                                   DELETE_COMPLETE                                                                                                           181.0s
 ⠿ NginxawsSg056000683b6f2cfa0NetworkIngress  DELETE_COMPLETE                                                                                                           169.0s
 ⠿ NginxawsLoadBalancer                       DELETE_COMPLETE                                                                                                           170.0s
 ⠿ NginxTaskDefinition                        DELETE_COMPLETE                                                                                                           155.0s
 ⠿ NginxServiceDiscoveryEntry                 DELETE_COMPLETE                                                                                                           128.0s
 ⠿ NginxTCP80Listener                         DELETE_COMPLETE                                                                                                            11.7s
 ⠿ NginxService                               DELETE_COMPLETE                                                                                                             9.4s
Invalid request provided: CreateService error: security group cannot be blank. (Service: Ecs, Status Code: 400, Request ID: b86808d8-ab60-4cb2-80b6-4858375aa619, Extended Request ID: null)```

If so, how do I get a copy of docker for mac with this patch in it?

**Comment by ndeloof** [comment]
@mottati this is a separate issue, please create a dedicated one I'll investigate

**Comment by mottati** [comment]
Thank you, here is the link: https://github.com/docker/compose-cli/issues/750

**Pull request merged**
