### PR TITLE
Update all headers and its checkers for year 2021

### PR DESCRIPTION
**Pull request by ulyssessouza**
**What I did**
Update all files with:
```sh
$ find . -type f \( -name "*Dockerfile" -o -name "*Makefile" -o -name "*.go" -o -name "*.sh" \) | xargs sed -i 's/Copyright 2020 Docker Compose CLI authors/Copyright 2021 Docker Compose CLI authors/g'
```

### CODE REVIEW

**Comment by gtardif** [comment]
is there a valid form that does not require updating all files every year ? 
Something like "since 2020" ?

**Comment by ndeloof** [comment]
Copyright date should reflect the time work took place on code, IMHO it doesn't make sense to update all files every year. Only new components/packages may use a refreshed copyright header to reflect work in progress.
That being said, this whole copyright headers are a non-sense to me as LICENSE is already set on repo, but INAL.

**Comment by thaJeztah** [comment]
Yes, changing 2020 to 2021 is definitely wrong. 

Copyright should either:

- "not" include a year
- include Year of first publication (2020 for this code?)
- only update year if significant changes are made to that file (in which case a range should be used `<year of first publication>` - `<year of last significant change>`)

Some projects also choose to omit the Year (as, especially with Git), year of "first publication" can be proven based on git history (e.g. https://github.com/containerd/containerd/blob/master/client.go#L2)
That said, I know there are some in the "camp" that including a Year makes it slightly "stronger"

**Comment by gtardif** [comment]
cf https://docker.slack.com/archives/C0111G2RCE4/p1614177320044400

**Review by ndeloof — CHANGES_REQUESTED** [review]
Copyright header should reflect the year code has been created, not legit to update it as a whole each and every year

**Comment by gtardif** [comment]
Closing for now as the change will not be updating year in copyright anyway. Need to confirm if we can remove year from all files and only keep it in the NOTICE at repo root

**Pull request closed without merging**
