### PR TITLE
Bump compose-go

### LINKED ISSUE #1917: Docker v2 Beta can't handle env file without "=" after variable name
**Description**

When you specify --env-file filename.env for the new docker-compose and the env file contains just variable names without "=" afterwards, the docker-compose command fails with "Can't separate key from value"

**Steps to reproduce the issue:**

1. Create `_docker.env` file with this content in a directory where you have a docker-compose file:
```
VARIABLE
```
2. Run `docker-compose up --env-file ${PATH}/_docker.env`

**Describe the results you received:**

The command fails with `Can't separate key from value` error

**Describe the results you expected:**

* It should not fail
* If VARIABLE is not defined in host, it should not be present in the container
* If VARIABLE is defined in host, it should be set in the container to the same value

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems that adding `=` after the variable fixes the problem:

```
VARIABLE=
```

This issue was first discovered in  https://github.com/apache/airflow/issues/16949 and workarounded in https://github.com/apache/airflow/pull/16950 by @oyarushe for Apache Airflow. 

**Output of `docker-compose --version`: ***
```
v2.0.0-beta.6
```

**Output of `docker version`:**
```
Docker Desktop: 3.5.2 on MacOS
```

### PR DESCRIPTION
**Pull request by lorenrh**
Signed-off-by: Lorena Rangel <lorena.rangel@docker.com>

**What I did**
Bump compose go!

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**
image

Related issue
Resolves #1917

### CODE REVIEW

**Review by mat007 — APPROVED** [review]
Yes!

**Comment by mat007** [comment]
Ah maybe it misses a `go mod tidy` or something? The linting failed: https://github.com/docker/compose-cli/pull/2002/checks?check_run_id=3278366958

**Comment by potiuk** [comment]
🐱

**Comment by potiuk** [comment]
Do you know when it's going to be released so that we can try it ?

**Comment by mat007** [comment]
@potiuk imminently 😁

**Comment by potiuk** [comment]
🤞

**Pull request merged**
