### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by ulyssessouza**

### CODE REVIEW

**Review by mat007 — APPROVED** [review]
Thanks!

**Comment by mat007** [comment]
CI failed though? 🤔

**Comment by mat007** [comment]
Do we still need to do this? I can see dependabot alerts all right now that they’re part of GitHub.

**Comment by hartwork** [comment]
> CI failed though? :thinking:

@mat007 the CI failure (should be addressed but) is unrelated.


> Do we still need to do this? I can see dependabot alerts all right now that they’re part of GitHub.

@mat007 Dependabot has been integrated with GitHub, yes, and that new file [configures](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates#enabling-dependabot-version-updates) that GitHub Dependabot should be active and what it's suppose to do.

**Pull request closed without merging**
