### PR TITLE
resolve build args on compose up --build

### PR DESCRIPTION
**Pull request by ndeloof**
**What I did**
Resolve build args from environment when running `docker compose up --build`

**Related issue**
close https://github.com/docker/compose-cli/issues/1665

### CODE REVIEW

**Review by lorenrh — APPROVED** [review]
🌮

**Review by gtardif — APPROVED** [review]

**Comment by SamuelMS** [comment]
@ndeloof I did a little digging but couldn't find anything about Docker's release cycle – do you have any guidance you can share on when this'll get pushed up to Docker for Mac? I'm glad there's a workaround (use `docker-compose` instead), but a few of our developers have run into this issue now.

**Comment by reagent** [comment]
Ran into this one today and upgraded Docker on Mac -- looks like this is fixed in `20.10.12` / `1.29.2`:

```
$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
$ docker --version
Docker version 20.10.12, build e91ed57
```

**Comment by tucomel** [comment]
the problem still persist here 
already using latest versions and the command 
`docker-compose build --build-arg ASPNETCORE_ENVIRONMENT=Development`
or
`docker-compose build --build-arg ENV=Development`
still not works 

image

**Comment by juan7732** [comment]
@tucomel That doesn't seem to be an issue with the problem mentioned here. You need to remove the whitespace after `ASPNETCORE_ENVIRONMENT` in your docker-compose file.
image
image

**Comment by F8ER** [comment]
> the problem still persist here already using latest versions and the command `docker-compose build --build-arg ASPNETCORE_ENVIRONMENT=Development` or `docker-compose build --build-arg ENV=Development` still not works
> 
> image

My apologies, quite off-topic, but just to clarify, is that Vim?

**Pull request merged**
